GPUAliases:
  - GPUName: TU104_GEFORCE_RTX_2080_REV__A
    alias: RTX2080
  - GPUName: TU104_GEFORCE_RTX_2080
    alias: RTX2080
  - GPUName: AD102_GEFORCE_RTX_4090
    alias: RTX4090
  - GPUName: GH100_H100_PCIE
    alias: H100
  - GPUName: GH100_H100L_94GB
    alias: H100
  - GPUName: GA102GL_RTX_A6000
    alias: RTXA6000
  - GPUName: AD104GL_L4
    alias: L4
  - GPUName: TU104GL_TESLA_T4
    alias: T4
  - GPUName: GA100_A100_PCIE_40GB
    alias: A100
  - GPUName: GA100_A100_PCIE_80GB
    alias: A100
  - GPUName: GV100GL_TESLA_V100_PCIE_16GB
    alias: V100
  - GPUName: GV100GL_TESLA_V100_PCIE_32GB
    alias: V100
  - GPUName: GH100_GH200_120GB___480GB
    alias: GH200
  - GPUName: GH100_GH200_144G_HBM3E
    alias: GH200
  - GPUName: AD102GL_RTX_6000_ADA_GENERATION
    alias: RTX6000ADA
  - GPUName: GB202GL_RTX_PRO_6000_BLACKWELL_SERVER_EDITION
    alias: RTXPRO6000
  - GPUName: AD102GL_L40G
    alias: L40G
  - GPUName: AD102GL_L40
    alias: L40
  - GPUName: AD102GL_L40S
    alias: L40S
  - GPUName: GA102GL_A40
    alias: A40
  - GPUName: GB110_GB300
    alias: GB300
  - GPUName: GB20B_GB10
    alias: GB10
  - GPUName: GB100_HGX_GB200
    alias: GB200
